FormKey: 00D519:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12504
EditorID: MantellaMainSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaRadiantEnabled
        Object: 00D51E:Mantella.esp
    Fragments:
    - FragmentIndex: 8
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_08
    - FragmentIndex: 7
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_07
    - FragmentIndex: 5
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_05
    - FragmentIndex: 2
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_02
    - FragmentIndex: 6
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_06
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_01
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_03
    - FragmentIndex: 4
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaMainSettingsTer_0700D519
      FragmentName: Fragment_Terminal_04
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Main Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose option
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: 'DEBUG : Stop all conversations'
  ResponseText:
    TargetLanguage: English
    Value: Close the Pipboy to complete.
  Type: DisplayText
  ItemId: 4
  DisplayText:
    TargetLanguage: English
    Value: This will end all Mantella effects running on NPCs.
- ItemText:
    TargetLanguage: English
    Value: Turn subtitles OFF
  Type: DisplayText
  ItemId: 5
  DisplayText:
    TargetLanguage: English
    Value: Turning Mantella dialogue subtitles OFF
- ItemText:
    TargetLanguage: English
    Value: Turn subtitles ON
  Type: DisplayText
  ItemId: 6
  DisplayText:
    TargetLanguage: English
    Value: Turning Mantella dialogue subtitles ON
- ItemText:
    TargetLanguage: English
    Value: Remove conversation activation option
  Type: DisplayText
  ItemId: 1
  DisplayText:
    TargetLanguage: English
    Value: The extra activation option for Mantella has been removed.
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x72DC04
    ComparisonValue: 1
    Data:
      MutagenObjectType: FunctionConditionData
      RunOnType: Reference
      Reference: 000014:Fallout4.esm
      Function: HasPerk
      ParameterOneRecord: 084DED:Mantella.esp
      ParameterOneNumber: 117984749
- ItemText:
    TargetLanguage: English
    Value: Add conversation activation option
  Type: DisplayText
  ItemId: 3
  DisplayText:
    TargetLanguage: English
    Value: >+
      The extra activation option for Mantella has been added.
  Conditions:
  - MutagenObjectType: ConditionFloat
    Unknown1: 0x72DC04
    Data:
      MutagenObjectType: FunctionConditionData
      RunOnType: Reference
      Reference: 000014:Fallout4.esm
      Function: HasPerk
      ParameterOneRecord: 084DED:Mantella.esp
      ParameterOneNumber: 117984749
- ItemText:
    TargetLanguage: English
    Value: Turn microphone OFF
  Type: DisplayText
  ItemId: 7
  DisplayText:
    TargetLanguage: English
    Value: >+
      Turning the microphone OFF. Use the dialogue hotkey to communicate with Mantella NPCs.
- ItemText:
    TargetLanguage: English
    Value: Turn microphone ON
  Type: DisplayText
  ItemId: 8
  DisplayText:
    TargetLanguage: English
    Value: >+
      Turning the microphone ON. Adjust the audio threshold if there are communication issues.

- ItemText:
    TargetLanguage: English
    Value: Restore defaults settings
  Type: DisplayText
  ItemId: 2
  DisplayText:
    TargetLanguage: English
    Value: 'Restoring settings to default. '
MajorFlags:
- 0x10
- 0x2000
