FormKey: 009FDC:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12504
EditorID: MantellaVisionSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaVisionSettingsT_07009FDC
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 9
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaVisionSettingsT_07009FDC
      FragmentName: Fragment_Terminal_09
    - FragmentIndex: 10
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaVisionSettingsT_07009FDC
      FragmentName: Fragment_Terminal_10
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Vision Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose option
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Turn auto vision analysis OFF
  Type: DisplayText
  ItemId: 9
  DisplayText:
    TargetLanguage: English
    Value: Turn automatic vision analysis OFF.
- ItemText:
    TargetLanguage: English
    Value: Turn auto Vision Analysis ON
  Type: DisplayText
  ItemId: 10
  DisplayText:
    TargetLanguage: English
    Value: >+
      Turn automatic vision analysis ON. An image of the player's field of view will be sent to the LLM after every reply. 


      Requires specific ChatML compatible LLM capable of vision analysis (e.g. ChatGPT4-o). 
- ItemText:
    TargetLanguage: English
    Value: Set image resolution (submenu)
  Type: SubmenuTerminal
  ItemId: 1
  Submenu: 009FDD:Mantella.esp
MajorFlags:
- 0x10
- 0x2000
