FormKey: 055E78:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12474
EditorID: MantellaEventTrackingSettings
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 5
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_05
    - FragmentIndex: 2
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_02
    - FragmentIndex: 6
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_06
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_01
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_03
    - FragmentIndex: 4
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaEventTrackingSe_07055E78
      FragmentName: Fragment_Terminal_04
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Event Tracking Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Event Tracking Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose an option
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Turn player event tracking OFF
  Type: DisplayText
  ItemId: 3
  DisplayText:
    TargetLanguage: English
    Value: >+
      Player event tracking is turned OFF

- ItemText:
    TargetLanguage: English
    Value: Turn player event tracking ON
  Type: DisplayText
  ItemId: 1
  DisplayText:
    TargetLanguage: English
    Value: >+
      Player event tracking is turned ON
- ItemText:
    TargetLanguage: English
    Value: NPC event tracking OFF
  Type: DisplayText
  ItemId: 2
  DisplayText:
    TargetLanguage: English
    Value: >+
      NPC event tracking is turned OFF


- ItemText:
    TargetLanguage: English
    Value: NPC event tracking ON
  Type: DisplayText
  ItemId: 4
  DisplayText:
    TargetLanguage: English
    Value: >+
      NPC event tracking is turned ON



- ItemText:
    TargetLanguage: English
    Value: F4SE Crosshair Tracking OFF (desktop only)
  Type: DisplayText
  ItemId: 5
  DisplayText:
    TargetLanguage: English
    Value: F4SE Crosshair Tracking tracking is turned OFF.
- ItemText:
    TargetLanguage: English
    Value: F4SE Crosshair Tracking ON (desktop only)
  Type: DisplayText
  ItemId: 6
  DisplayText:
    TargetLanguage: English
    Value: F4SE Crosshair Tracking tracking is turned ON.
MajorFlags:
- 0x10
- 0x2000
