FormKey: 009FDD:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12504
EditorID: MantellaResolutionSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaResolutionSetti_07009FDD
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 9
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResolutionSetti_07009FDD
      FragmentName: Fragment_Terminal_09
    - FragmentIndex: 10
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResolutionSetti_07009FDD
      FragmentName: Fragment_Terminal_10
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaResolutionSetti_07009FDD
      FragmentName: Fragment_Terminal_01
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Resolution Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose option from the below for the image resolution to be sent to the LLM. A higher resolution will spend more tokens and have longer response times but will be more precise.
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Auto
  Type: DisplayText
  ItemId: 9
  DisplayText:
    TargetLanguage: English
    Value: >+
      Image resolution sent to the LLM is set to auto (default).
- ItemText:
    TargetLanguage: English
    Value: Low
  Type: DisplayText
  ItemId: 10
  DisplayText:
    TargetLanguage: English
    Value: >+
      Image resolution sent to the LLM is set to low.
- ItemText:
    TargetLanguage: English
    Value: High
  Type: DisplayText
  ItemId: 1
  DisplayText:
    TargetLanguage: English
    Value: Image resolution sent to the LLM is set to high.
MajorFlags:
- 0x10
- 0x2000
