FormKey: 00D51D:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12474
EditorID: MantellaSettingsTerminal
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 5
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      FragmentName: Fragment_Terminal_05
    - FragmentIndex: 6
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      FragmentName: Fragment_Terminal_06
    - FragmentIndex: 1
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      FragmentName: Fragment_Terminal_01
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      FragmentName: Fragment_Terminal_03
    - FragmentIndex: 4
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaSettingsTermina_0700D51D
      FragmentName: Fragment_Terminal_04
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: Choose menu
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Main Settings
  Type: SubmenuTerminal
  ItemId: 1
  Submenu: 00D519:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: Radiant Settings
  Type: SubmenuTerminal
  ItemId: 2
  Submenu: 015DBF:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: Event Tracking Settings
  Type: SubmenuTerminal
  ItemId: 3
  Submenu: 055E78:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: NPC Action Settings (Experimental)
  Type: SubmenuTerminal
  ItemId: 4
  Submenu: 05E71A:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: HTTP Settings
  Type: SubmenuTerminal
  ItemId: 5
  Submenu: 08099C:Mantella.esp
- ItemText:
    TargetLanguage: English
    Value: Hotkeys Settings (Desktop Only)
  Type: SubmenuTerminal
  ItemId: 6
  Submenu: 084DEE:Mantella.esp
MajorFlags:
- 0x10
- 0x2000
