FormKey: 08099C:Mantella.esp
MajorRecordFlagsRaw: 8208
VersionControl: 12413
EditorID: MantellaHTTPSettings
Fallout4MajorRecordFlags:
- 0x10
- 0x2000
VirtualMachineAdapter:
  ScriptFragments:
    Script:
      Name: Fragments:Terminals:TERM_MantellaHTTPSettings_0708099C
      Properties:
      - MutagenObjectType: ScriptObjectProperty
        Name: MantellaQuest
        Object: 000F99:Mantella.esp
    Fragments:
    - FragmentIndex: 3
      Unknown2: 1
      ScriptName: Fragments:Terminals:TERM_MantellaHTTPSettings_0708099C
      FragmentName: Fragment_Terminal_03
ObjectBounds:
  First: -18, -52, 86
  Second: 21, 0, 135
HeaderText:
  TargetLanguage: English
  Value: Mantella - HTTP Settings
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Event Tracking Settings'
Model:
  File: Furniture\Terminals\TerminalWall01.nif
  Data: 0x0400000000000000000000000000000000000000
Keywords:
- 0A56D7:Fallout4.esm
- 06D5BB:Fallout4.esm
- 0C2022:Fallout4.esm
PNAM: 0xCC4C3300
FNAM: 0x0000
Holotapes: []
Flags:
- HasModel
WorkbenchData: 0x00
MarkerModel: Markers\MarkerWallTerminal3rdP.nif
MarkerParameters:
- Enabled: True
  Offset: 0, -86, 0
  EntryTypes:
  - Front
  - Behind
  - Right
  - Left
  - Other
  - 0x20
  - 0x40
  - 0x80
  Unknown: 0xFFFFFF
BodyTexts:
- Text:
    TargetLanguage: English
    Value: 'Choose an option. '
MenuItems:
- ItemText:
    TargetLanguage: English
    Value: Set HTTP Port
  Type: DisplayText
  ItemId: 3
  DisplayText:
    TargetLanguage: English
    Value: Close the Pipboy menu to set the HTTP port
MajorFlags:
- 0x10
- 0x2000
