FormKey: 00D51A:Mantella.esp
VersionControl: 12341
EditorID: MantellaSettingsHolotape
ObjectBounds:
  First: -3, -3, 0
  Second: 3, 3, 1
PreviewTransform: 0995A5:Fallout4.esm
Name:
  TargetLanguage: English
  Value: '[Settings] Mantella Settings'
Model:
  File: Props\Holotape_Prop.nif
  Data: 0x0400000000000000000000000000000000000000
PickUpSound: 0BBFA8:Fallout4.esm
PutDownSound: 0BBFA9:Fallout4.esm
Value: 1
Data:
  MutagenObjectType: HolotapeTerminal
  Terminal: 00D51D:Mantella.esp
