FormKey: 00D51B:Mantella.esp
VersionControl: 12341
EditorID: co_MantellaSettingsHolotape
Description:
  TargetLanguage: English
  Value: ''
CreatedObject: 00D51A:Mantella.esp
WorkbenchKeyword: 102158:Fallout4.esm
Categories:
- 06980C:Fallout4.esm
CreatedObjectCounts:
- Count: 1
